### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by ed-freitas** [blogscroll/blogscroll#10]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://edfreitas.me

**What category does the site belong to?**
Take a look at https://blogscroll.com or suggest your own category.
Technology

**Comment by dend** [comment]
Added: 85929ee179d7e565febb494bf2a3f5afcc3d9f87

Thank you!
