### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by slamethendry** [blogscroll/blogscroll#12]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://hendry.id

**What category does the site belong to?**
General / Random Personal Thoughts

**Comment by dend** [comment]
Thanks for the submission, @slamethendry! This is actually an interesting entry in that we don't yet have a category for generic sites. But I still want to make sure that we include it. What do you think about a category named **Learning**?

**Comment by slamethendry** [comment]
Oops, sorry I missed this.  Yeah sure, I think 'Learning' sounds good actually.  Thanks.
