### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by coreyprophitt** [blogscroll/blogscroll#13]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**

https://prophitt.me

**What category does the site belong to?**

Technology

**Comment by coreyprophitt** [comment]
I added a PR for this: https://github.com/blogscroll/blogscroll/pull/17

**Comment by dend** [comment]
Thank you @coreyprophitt - looks good, I merged it! 🎉
