### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by oddlinks** [blogscroll/blogscroll#134]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://oddlinks.com

**What category does the site belong to?**
personal

Thanks for maintaining this really cool project! Cheers, Chris :)

**Comment by cawblog** [comment]
Hoping this isn't the wrong place for this - I changed the name of the blog from oddlinks.com to caw.blog. Any chance you could update the listing to "Chris (caw.blog)" or just "caw.blog"? Thanks!
