### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by jdtonkin** [blogscroll/blogscroll#170]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://predirections.substack.com

**What category does the site belong to?**
Science / Environment / Climate

**Comment by jdtonkin** [comment]
Commenting to remove stale tag

**Comment by dend** [comment]
@jdtonkin will have to close this due to it not being on its own domain. See: https://github.com/blogscroll/blogscroll?tab=readme-ov-file#can-i-add-any-site

Feel free to re-open once you host on your own domain.
