### ISSUE TITLE
swimburger.net

### ISSUE THREAD

**Issue by Swimburger** [blogscroll/blogscroll#4]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://swimburger.net

**What category does the site belong to?**
Technology (.NET, Azure, PowerShell, Umbraco, web, and more)

**Comment by dend** [comment]
Covered in 7641d78. Thanks! 🙌
