### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by dotcoma** [blogscroll/blogscroll#40]
Hi

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://www.dotcoma.it/

**What category does the site belong to?**
Tech (business side and what tech is doing to society; mostly in Italian, some posts in English)

**Comment by dend** [comment]
Declining because it's not in English.

**Comment by dotcoma** [comment]
What about... ?
https://www.dotcoma.it/english
