### ISSUE TITLE
[SITE REQUEST] vgel.me

### ISSUE THREAD

**Issue by vgel** [blogscroll/blogscroll#45]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq ✅ 

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://vgel.me

**What category does the site belong to?**
Technology

**Comment by komali2** [comment]
https://vgel.me/hoverator/ this is infurating lol i can get like 180m at most
