### ISSUE TITLE
[SITE REQUEST] zck.org

### ISSUE THREAD

**Issue by zck** [blogscroll/blogscroll#47]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://zck.org/

**What category does the site belong to?**
Technology

**Comment by komali2** [comment]
i noticed us emacs enjoyers always have the cleanest sites ;)

**Comment by zck** [comment]
Cool, thank you!
