### ISSUE TITLE
[SITE REQUEST] blog.singleton.io

### ISSUE THREAD

**Issue by dps** [blogscroll/blogscroll#48]
**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://blog.singleton.io/

**What category does the site belong to?**
Technology [though I will note it's a bit eclectic and crosses over into cooking and wine making - it's my little corner of the web, mostly technology!]

**Comment by komali2** [comment]
https://blog.singleton.io/posts/2022-10-17-otp-on-wrist/ sick project, do you still wear the watch lol?
