### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by DavidAnson** [blogscroll/blogscroll#5]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://dlaa.me/

**What category does the site belong to?**
TECHNOLOGY

**Comment by dend** [comment]
Covered in 8898e93 - thank you! 👋

**Comment by DavidAnson** [comment]
Thank you for doing this.
