### ISSUE TITLE
[SITE REQUEST] hjr265.me - Mahmud Ridwan

### ISSUE THREAD

**Issue by hjr265** [blogscroll/blogscroll#50]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq ✔️

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://hjr265.me

**What category does the site belong to?**
Technology

**Comment by komali2** [comment]
hell yeah simple sites!
