### ISSUE TITLE
[SITE REQUEST] muhammadraza.me - Muhammad

### ISSUE THREAD

**Issue by mraza007** [blogscroll/blogscroll#51]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
[Link to my blog](https://muhammadraza.me/)

**What category does the site belong to?**
- Technology

**Comment by komali2** [comment]
love the style of this

**Comment by mraza007** [comment]
Well thank you

I’m glad you liked it
