### ISSUE TITLE
[ SITE REQUEST ] www.randomnoun.com

### ISSUE THREAD

**Issue by knoxg** [blogscroll/blogscroll#52]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

Is the site you are adding one that you manage?
Yes

Where is the site located?
http://www.randomnoun.com

What category does the site belong to?
Technology

**Comment by dend** [comment]
Site needs to be on HTTPS with a valid certificate. Please re-open when done.

**Comment by knoxg** [comment]
No worries, is now available on HTTPS at https://www.randomnoun.com
