### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by akhanrepo** [blogscroll/blogscroll#6]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://akhan.me

**What category does the site belong to?**
Technology

**Comment by dend** [comment]
Added: 85929ee179d7e565febb494bf2a3f5afcc3d9f87

Thank you!
