### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by andrewkorf** [blogscroll/blogscroll#72]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
www.korf.co

**What category does the site belong to?**
UX & Design

**Comment by dend** [comment]
@andrewkorf just to make sure that I fully understand the submission, is this your _personal_ site or the _company_ site? I see "& Co." in the title.
