### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by scotbuff** [blogscroll/blogscroll#74]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://irongeek.net

**What category does the site belong to?**
Technology

**Comment by dend** [comment]
@scotbuff can you please clarify your name (not a nickname/alias) that needs to be listed for the blog?

**Comment by scotbuff** [comment]
I updated my profile with my full name - Scott Buffington
