### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by Phileosopher** [blogscroll/blogscroll#78]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes, to all 5

**Where is the site located?**
https://gainedin.site
https://adequate.life
https://trendless.tech
https://entertaining.space
https://notageni.us

**What category does the site belong to?**
Philosophy
Life Tips
Technology
Fun
Life Tips

**Comment by Phileosopher** [comment]
Not sure if I'm supposed to have 5 different issues, or just 1, so I took the decluttered route.

**Comment by dend** [comment]
@Phileosopher to make sure that we're not flooding the blog feed with multiple sites from the same individual, is there _one_ personal blog you would like included?

**Comment by Phileosopher** [comment]
Yep, https://stucky.tech

You can throw it in the "Personal" section.

**Comment by dend** [comment]
Published.
