### ISSUE TITLE
Feature: Adding contributors section to the readme.md file

### ISSUE THREAD

**Issue by kalyani2003** [blogscroll/blogscroll#85]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create. Any contributions make are greatly appreciated, for that we need to add new section for contributors and adding to the readme file! Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/blogscroll/blogscroll/assets/84217977/55ebe0ab-507f-4d1f-8cca-977336a437ea)

**Comment by kalyani2003** [comment]
@dend  kindly assign me this #85 issue , I want to work on it. and it will surely good contribution!

**Comment by dend** [comment]
Thanks for the suggestion. Currently I have no plans on including that in the README.
