### ISSUE TITLE
[SITE REQUEST]

### ISSUE THREAD

**Issue by lazaruscorporation** [blogscroll/blogscroll#97]
Make sure to read the FAQ before opening an issue: https://github.com/blogscroll/blogscroll#-faq

**Is the site you are adding one that you manage?**
Yes

**Where is the site located?**
https://www.lazaruscorporation.co.uk/

**What category does the site belong to?**
ART-AND-CULTURE

**Comment by dend** [comment]
Thank you for reaching out @lazaruscorporation. Unfortunately, I can't include this in the collection because of NSFW content on the site. Nothing inherently wrong with the art, just likely not the best for this directory that people browse from work machines.

**Comment by lazaruscorporation** [comment]
Hi @dend  - I completely understand - no problem at all
